### ISSUE TITLE
Tracking Issue: Lints

### ISSUE THREAD

**Issue by elenakrittik** [elenakrittik/gdtk#58]
This issue tracks progress on implementing various rules, including those found in Godot itself as well as in senior gdtk. Feel free to point out missing rules by opening a new issue that mentions this one.

## Syntax Rules

These are rules that check for semantically-invalid constructs, such as usage of `self` in `static func`s.

- [ ] "namespace" is a currently unusable keyword reserved for future compatibility; [see the associated GIP](https://github.com/godotengine/godot-proposals/issues/1566)
- [ ] "trait" is a currently unusable keyword reserved for future compatibility; [see the associated GIP](https://github.com/godotengine/godot-proposals/issues/6416)
- [ ] "yield" is a Godot 3.x-only keyword, but `gdtk` only supports Godot 4.x. Use `await` instead.
